title: Wumpus
author: Icara
email: aayus1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Antarctica is precious and you can't change my mind, you rotten boiled egg.

# social links
twitter_username: twitter_is_for_scrubs
github_username:  Icara

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
